### ISSUE TITLE
tab complite comes but the command is still blocked 

### ISSUE THREAD

**Issue by Hiradpi** [RayzsYT/ProAntiTab#3]
```
global:
  commands:
  - lobby
  - msg 
  - tell 
  - m 
  - r
  - reply
  - report
  ignored-servers:
  - auth
  servers:
    lobby:
      commands:
      - queue
      - kitpvp
      - thepit
      - skywars
    kitpvp:
      commands:
      - leave
      - spawn
      - addbounty
groups: []
```
this is my waterfall proxy's configuration

in the kitpvp server the tabcomplite comes but when executed it blocks it 
what am i missing here ?
