### ISSUE TITLE
Sub command whitelsitng not working

### ISSUE THREAD

**Issue by lerokko** [RayzsYT/ProAntiTab#8]
All my commands setup with the plugin have no sub command argument suggestions. Regardless of what I put the behind the commands on the config (as showed on the spigot.org description page) as soon a something is put behind the command in the config file it will not be added to the suggestion list at all.

I am using (not behind a proxy. Its a standalone server):
`Paper version 1.21.4-118-main@73f7736 (2025-01-18T13:37:35Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)`
with ProAntiTab version:
`ProAntiTab version 1.9.0`

My storage.yml
```yml
global:
  commands:
      - accesstrust %online_players%
      - afk %online_players%
      - at %online_players%
      - confirm
      - containertrust
      - ct
      - discord
      - explosions
      - hide
      - ignore %online_players%
      - ignorelist
      - joindate
      - link Minecraft
      - map Minecraft
      - me Minecraft
      - msg %online_players%
      - permissiontrust %online_players%
      - pt %online_players%
      - r
      - reply
      - seen %online_players%
      - show
      - sit
      - stats
      - t %online_players%
      - takemyslot
      - tl
      - tps
      - trust %online_players%
      - trustlist
      - unignore %online_players%
      - w %online_players%
```

![Image](https://github.com/user-attachments/assets/82cc2ab8-5b9f-4361-b989-461ecdd05756)

![Image](https://github.com/user-attachments/assets/a0af7537-39b1-4087-89e8-5f7fac1fd7b1)

![Image](https://github.com/user-attachments/assets/598f9c79-699e-4fcc-898d-e4f60ff6254f)

A lot of my command need auto completion (usually the payer list) but a coreprotect lookup would unfeasible without tab completion.
If you need any more information I gladly provide them. Obligatory disclaimer that this does not happen without the plugin installed or when given the proantitab.* permission.

**Comment by RayzsYT** [comment]
A yeah, I see what might be the reason for that.

You see... to use the sub-arguments in whitelist mode, you also have to add the base of the command.

Here's an example:

If you want to enable the ``help discord`` command, then you also need to add ``help``, like in this shown example:

```yaml
- help
- help Minecraft
```

It's described on the Spigot ressource page in the 'sub arguments example spoiler'. 

Yeah, totally my bad for not descibing it better on the wiki or in the documentation. 

Sorry for that. xd


Please lemme know if this solves it or not! ^^

**Comment by RayzsYT** [comment]
Here's the spoiler I was referring to:

![Image](https://github.com/user-attachments/assets/a8e731d7-7077-4e81-a62f-3c3f01728150)

**Comment by lerokko** [comment]
Thank you for the quick response! That seemed to work now. However the auto-completion only says `[<args>]` even when give a list like below. This goes for the first or any other parameter of the co command. I hope you can see why it renders a [complex command like that](https://docs.coreprotect.net/commands/#co-lookup) almost unusable. Can this be fixed?

storage.yml [excerpt]
```yml
  moderator:
    priority: 20
    commands:
      - co
      - co inspect
      - co lookup
      - co near
      - co status
```

Only `[<args>]` is suggested instead of the words defined in the storage.yml
![Image](https://github.com/user-attachments/assets/09c7f179-ff89-4561-8fea-251452106f17)

Normally CoreProtect should now suggest position agnostic key parameters like `include:` or `time:` and even suggest vales for said keys for those. But no suggestions are given.
![Image](https://github.com/user-attachments/assets/cdf09457-0ce9-408c-a622-f54191da0c78)

In my use case all plugins are smart enough to not suggest sub commands the player does not have access too. So I would be okay with ProAntitab just allowing to relay the unmodified **SUB**-command suggestions of any whitelisted root command. As sub command options that the players will not have access to would not be show regardless. In theory I only need it to restrict the initial root (top level) command list.

**Comment by RayzsYT** [comment]
I see that you are using the sub arguments for a specific group only. If I might ask, could you please type ``/pat perms <user>`` and check which PAT-related permissions this user got?

Also, is the user able to execute these commands, or does it affect both suggestion & execution?

**Comment by lerokko** [comment]
It seems to affect tab completion. All commands still work as expected how they are setup with luckperms.

`All of MinecraftEarth's PAT-related permission: proantitab.group.moderator, proantitab.group.trusted, proantitab.group.player`

I was using the priority system to determine which tab-list to use (I was first under the assumption that all tab list the player had perms for would be joined/merged but that seemed only be the case of default+the highest priority group).
It is that way cause all my ranks are setup on 1 track/chain. Do you recommend to deny the previous' ranks tab group permission?

**Comment by RayzsYT** [comment]
I apologize for my delayed answer. 



**About PAT's priority system:**
A player might be assigned to two groups ``verified`` and ``unverified`` for example.
The group ``verified`` has a priority of ``1`` and the ``unverified`` group has a priority of ``2``.
Because the player is in both groups, only the commands from the group with the ``lower`` priority will show up for the player.
The commands in the group with the higher priority number is being ignored and the player won't inherit any commands from that group.

Example:
```yaml
groups:
  unverified:
    priority: 2
    commands:
      - hub
  verified:
    priority: 1
    commands:
      - msg
```
The player has the permission ``proantitab.group.verified`` and ``proantitab.group.unverified``.
If both groups would have the exact same priority, then the player could use ``/hub`` and ``/msg``.

But in the shown example, both priorities are different. With that, the player can only see and execute ``/msg``.
All the other commands from the general list will be added to the player automatically of course. ^^



**About the issue with CoreProtect:**
I tried to recreate the bug and actually was able to find out what might causes this confusion.

Instead of trying it with multiple groups and different priorities, I tried it with one group and it turns out that you were not even meant to execute this command in the first place. (Short: Yea sry, it was a bug ;c )
This also might be the reason why you couldn't tab-complete any of the options but still execute them.
I fixed it and linked the new jar to bottom of the comment.

Could you please do me a favor and set every group priority to ``1`` and use this custom made version of ProAntiTab instead?
I really would like to know how the plugin will react to that change.

Of course, if everything turns out to be working just fine, you can also experiment with the priority system a bit. ^^
Just let me know if you have any questions about the priority system.

https://github.com/RayzsYT/ProAntiTab/releases/tag/v1.9.1-Experimental
